service: dazser-signatures

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  timeout: 60
  memorySize: 512
  environment:
    DB_HOST: ${ssm:/api/sql/host~true}
    DB_USER: ${ssm:/api/sql/user~true}
    DB_PASS: ${ssm:/api/sql/pass~true}

functions:
  signatures:
    handler: handler.runner
    events:
      - schedule: cron(0 7 * * ? *)
